// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_TB12KIKxVHTaApnfpgRoU7KMPiau-Vw',
    appId: '1:716353325274:web:32b27d63e2a9a8109d3de3',
    messagingSenderId: '716353325274',
    projectId: 'egc-project-a2037',
    authDomain: 'egc-project-a2037.firebaseapp.com',
    storageBucket: 'egc-project-a2037.appspot.com',
    measurementId: 'G-F8Y16RYS1N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBByvRF84pQSdKTabEtVlwu3QTXqXkR_6A',
    appId: '1:716353325274:android:7791dcec4ea873579d3de3',
    messagingSenderId: '716353325274',
    projectId: 'egc-project-a2037',
    storageBucket: 'egc-project-a2037.appspot.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_TB12KIKxVHTaApnfpgRoU7KMPiau-Vw',
    appId: '1:716353325274:web:a065c08a1824dcfc9d3de3',
    messagingSenderId: '716353325274',
    projectId: 'egc-project-a2037',
    authDomain: 'egc-project-a2037.firebaseapp.com',
    storageBucket: 'egc-project-a2037.appspot.com',
    measurementId: 'G-GMYZD0F6J6',
  );
}
